version: '3'
services:
  zookeeper:
    image: eventuateio/eventuateio-local-zookeeper:0.30.0.RELEASE
    ports:
      - 12181:2181
      - 12888:2888
      - 13888:3888
  kafka:
    image: eventuateio/eventuateio-local-kafka:0.30.0.RELEASE
    ports:
      - 19092:9092
    depends_on:
      - zookeeper
    environment:
      - ADVERTISED_HOST_NAME=${DOCKER_HOST_IP?DOCKER_HOST_IP must be set}
      - KAFKA_HEAP_OPTS=-Xmx192m -Xms192m
      - ZOOKEEPER_SERVERS=zookeeper:2181
  mysql:
    build: ./mysql
    ports:
      - 13306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
  tram-cdc-service:
    image: eventuateio/eventuate-tram-cdc-mysql-service:0.20.0.RELEASE
    ports:
      - "8099:8080"
    depends_on:
      - mysql
      - kafka
    environment:
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181

      EVENTUATE_CDC_PIPELINE_PIPELINE1_TYPE: eventuate-local
      EVENTUATE_CDC_PIPELINE_PIPELINE1_READER: reader1

      EVENTUATE_CDC_PIPELINE_PIPELINE2_TYPE: eventuate-tram
      EVENTUATE_CDC_PIPELINE_PIPELINE2_READER: reader2

      EVENTUATE_CDC_READER_READER1_TYPE: mysql-binlog
      EVENTUATE_CDC_READER_READER1_DATASOURCEURL: jdbc:mysql://mysql:3306/eventuate
      EVENTUATE_CDC_READER_READER1_DATASOURCEUSERNAME: mysqluser
      EVENTUATE_CDC_READER_READER1_DATASOURCEPASSWORD: mysqlpw
      EVENTUATE_CDC_READER_READER1_DATASOURCEDRIVERCLASSNAME: com.mysql.jdbc.Driver
      EVENTUATE_CDC_READER_READER1_LEADERSHIPLOCKPATH: /eventuate/cdc/leader/eventuatelocal
      EVENTUATE_CDC_READER_READER1_CDCDBUSERNAME: root
      EVENTUATE_CDC_READER_READER1_CDCDBPASSWORD: rootpassword
      EVENTUATE_CDC_READER_READER1_READOLDDEBEZIUMDBOFFSETSTORAGETOPIC: "false"
      EVENTUATE_CDC_READER_READER1_MYSQLBINLOGCLIENTUNIQUEID: 1
      EVENTUATE_CDC_READER_READER1_OFFSETSTOREKEY: MySqlBinlog
      EVENTUATE_CDC_READER_READER1_OFFSETSTORAGETOPICNAME: db.history.eventuate.local

      EVENTUATE_CDC_READER_READER2_TYPE: mysql-binlog
      EVENTUATE_CDC_READER_READER2_DATASOURCEURL: jdbc:mysql://mysql:3306/eventuate
      EVENTUATE_CDC_READER_READER2_DATASOURCEUSERNAME: mysqluser
      EVENTUATE_CDC_READER_READER2_DATASOURCEPASSWORD: mysqlpw
      EVENTUATE_CDC_READER_READER2_DATASOURCEDRIVERCLASSNAME: com.mysql.jdbc.Driver
      EVENTUATE_CDC_READER_READER2_LEADERSHIPLOCKPATH: /eventuate/cdc/leader/eventuatetram
      EVENTUATE_CDC_READER_READER2_CDCDBUSERNAME: root
      EVENTUATE_CDC_READER_READER2_CDCDBPASSWORD: rootpassword
      EVENTUATE_CDC_READER_READER2_READOLDDEBEZIUMDBOFFSETSTORAGETOPIC: "false"
      EVENTUATE_CDC_READER_READER2_MYSQLBINLOGCLIENTUNIQUEID: 2
      EVENTUATE_CDC_READER_READER2_OFFSETSTOREKEY: MySqlBinlog
      EVENTUATE_CDC_READER_READER2_OFFSETSTORAGETOPICNAME: db.history.eventuate.tram

  ftgo-consumer-service:
    build: ./ftgo-consumer-service
    ports:
      - "8081:8080"
    depends_on:
      - mysql
      - kafka
      - tram-cdc-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/ftgoconsumerservice
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: mysqlpw
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      JAVA_OPTS: -Xmx192m
      SPRING_SLEUTH_ENABLED: "true"
      SPRING_SLEUTH_SAMPLER_PROBABILITY: 1
      SPRING_ZIPKIN_BASE_URL: http://zipkin:9411/
  ftgo-order-service:
    build: ./ftgo-order-service
    ports:
      - "8082:8080"
    depends_on:
      - mysql
      - kafka
      - tram-cdc-service
      - zipkin
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/ftgoorderservice
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: mysqlpw
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      JAVA_OPTS: -Xmx192m
      SPRING_SLEUTH_ENABLED: "true"
      SPRING_SLEUTH_SAMPLER_PROBABILITY: 1
      SPRING_ZIPKIN_BASE_URL: http://zipkin:9411/
  ftgo-kitchen-service:
      build: ./ftgo-kitchen-service
      ports:
        - "8083:8080"
      depends_on:
        - mysql
        - kafka
        - zookeeper
        - tram-cdc-service
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql/ftgokitchenservice
        SPRING_DATASOURCE_USERNAME: mysqluser
        SPRING_DATASOURCE_PASSWORD: mysqlpw
        SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
        EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
        EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
        JAVA_OPTS: -Xmx192m
        SPRING_SLEUTH_ENABLED: "true"
        SPRING_SLEUTH_SAMPLER_PROBABILITY: 1
        SPRING_ZIPKIN_BASE_URL: http://zipkin:9411/
  ftgo-restaurant-service:
      build: ./ftgo-restaurant-service
      ports:
        - "8084:8080"
      depends_on:
        - mysql
        - kafka
        - zookeeper
        - tram-cdc-service
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql/ftgorestaurantservice
        SPRING_DATASOURCE_USERNAME: mysqluser
        SPRING_DATASOURCE_PASSWORD: mysqlpw
        SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
        EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
        EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
        JAVA_OPTS: -Xmx192m
        SPRING_SLEUTH_ENABLED: "true"
        SPRING_SLEUTH_SAMPLER_PROBABILITY: 1
        SPRING_ZIPKIN_BASE_URL: http://zipkin:9411/
  ftgo-accounting-service:
        build: ./ftgo-accounting-service
        ports:
          - "8085:8080"
        depends_on:
          - mysql
          - kafka
          - zookeeper
        environment:
          SPRING_DATASOURCE_URL: jdbc:mysql://mysql/ftgoaccountingservice
          SPRING_DATASOURCE_USERNAME: mysqluser
          SPRING_DATASOURCE_PASSWORD: mysqlpw
          SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
          EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
          EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
          JAVA_OPTS: -Xmx192m
          SPRING_SLEUTH_ENABLED: "true"
          SPRING_SLEUTH_SAMPLER_PROBABILITY: 1
          SPRING_ZIPKIN_BASE_URL: http://zipkin:9411/
  ftgo-order-history-service:
        build: ./ftgo-order-history-service
        ports:
          - "8086:8080"
        depends_on:
          - kafka
          - zookeeper
          - tram-cdc-service
          - dynamodblocal
          - dynamodblocal-init
        environment:
          EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
          EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
          AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-id_key}
          AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-access_key}
          AWS_DYNAMODB_ENDPOINT_URL: http://dynamodblocal:8000
          AWS_REGION: ${AWS_REGION:-us-west-2}
          JAVA_OPTS: -Xmx192m
          SPRING_SLEUTH_ENABLED: "true"
          SPRING_SLEUTH_SAMPLER_PROBABILITY: 1
          SPRING_ZIPKIN_BASE_URL: http://zipkin:9411/
  ftgo-api-gateway:
    build: ./ftgo-api-gateway
    ports:
      - "8087:8080"
    environment:
      ORDER_DESTINATIONS_ORDERSERVICEURL: http://ftgo-order-service:8080
      ORDER_DESTINATIONS_ORDERHISTORYSERVICEURL: http://ftgo-order-history-service:8080
      CONSUMER_DESTINATIONS_CONSUMERSERVICEURL: http://ftgo-consumer-service:8080
      JAVA_OPTS: -Xmx192m
      SPRING_SLEUTH_ENABLED: "true"
      SPRING_SLEUTH_SAMPLER_PROBABILITY: 1
      SPRING_ZIPKIN_BASE_URL: http://zipkin:9411/

  ftgo-api-gateway-graphql:
    build: ./ftgo-api-gateway-graphql
    ports:
      - "8088:3000"
    environment:
      ORDER_HISTORY_SERVICE_URL: http://ftgo-order-history-service:8080
      CONSUMER_SERVICE_URL: http://ftgo-consumer-service:8080
      RESTAURANT_SERVICE_URL: http://ftgo-restaurant-service:8080

  zipkin:
      image: openzipkin/zipkin:2.5.0
      ports:
       - "9411:9411"
      environment:
        JAVA_OPTS: -Xmx128m

  dynamodblocal:
    build: ./dynamodblocal
    ports:
     - "8000:8000"
    environment:
      JAVA_OPTS: -Xmx128m

  dynamodblocal-init:
    build: ./dynamodblocal-init
    depends_on:
      - dynamodblocal
    restart: on-failure
    environment:
      AWS_DYNAMODB_ENDPOINT_URL: http://dynamodblocal:8000
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-id_key}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-access_key}
      AWS_REGION: ${AWS_REGION:-us-west-2}
